### ISSUE TITLE
Training code ?

### ISSUE THREAD

**Issue by bruinxiong** [ElegantGod/SSHA#4]
Do you release the training code of SSH with Alignment ?

**Comment by ElegantGod** [comment]
The training code are from [deepinsight](https://github.com/deepinsight/mxnet-SSH), just making small changes.

**Comment by bruinxiong** [comment]
@ElegantGod Thank you, but the codes from deepinsight only focuses on reproduction of SSH, how to implement landmark part for alignment during training ? Can you give some comments ? or do you mind to share your codes ? Thanks!

**Comment by ElegantGod** [comment]
@bruinxiong training code: [mxnet-SSHA](https://github.com/ElegantGod/mxnet-SSHA)

**Comment by ysc703** [comment]
@ElegantGod Hi, the code is loss.
